package com.slf.engine.bo;

import com.slf.engine.base.BaseObj;

public class LsDbdx extends BaseObj {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.DBDXID
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private Long dbdxid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.DBGJZ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private String dbgjz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.YXSJ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private String yxsj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.SXSJ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private String sxsj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.DJDBCS
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private Integer djdbcs;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.ZDBCS
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private Integer zdbcs;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.CGCSHF
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private String cgcshf;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.DBSXHF
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private String dbsxhf;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.HFNR
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private String hfnr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.ZT
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private String zt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.CJRQ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private String cjrq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.CJSJ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private String cjsj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.DLID
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private Long dlid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.DBLB
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private String dblb;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.JMTX
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private String jmtx;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.DXTX
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private String dxtx;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DBDX.DXTXDH
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    private String dxtxdh;
    
    private Long hdmbid;

    public Long getHdmbid() {
		return hdmbid;
	}

	public void setHdmbid(Long hdmbid) {
		this.hdmbid = hdmbid;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.DBDXID
     *
     * @return the value of LS_DBDX.DBDXID
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public Long getDbdxid() {
        return dbdxid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.DBDXID
     *
     * @param dbdxid the value for LS_DBDX.DBDXID
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setDbdxid(Long dbdxid) {
        this.dbdxid = dbdxid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.DBGJZ
     *
     * @return the value of LS_DBDX.DBGJZ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public String getDbgjz() {
        return dbgjz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.DBGJZ
     *
     * @param dbgjz the value for LS_DBDX.DBGJZ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setDbgjz(String dbgjz) {
        this.dbgjz = dbgjz == null ? null : dbgjz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.YXSJ
     *
     * @return the value of LS_DBDX.YXSJ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public String getYxsj() {
        return yxsj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.YXSJ
     *
     * @param yxsj the value for LS_DBDX.YXSJ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setYxsj(String yxsj) {
        this.yxsj = yxsj == null ? null : yxsj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.SXSJ
     *
     * @return the value of LS_DBDX.SXSJ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public String getSxsj() {
        return sxsj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.SXSJ
     *
     * @param sxsj the value for LS_DBDX.SXSJ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setSxsj(String sxsj) {
        this.sxsj = sxsj == null ? null : sxsj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.DJDBCS
     *
     * @return the value of LS_DBDX.DJDBCS
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public Integer getDjdbcs() {
        return djdbcs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.DJDBCS
     *
     * @param djdbcs the value for LS_DBDX.DJDBCS
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setDjdbcs(Integer djdbcs) {
        this.djdbcs = djdbcs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.ZDBCS
     *
     * @return the value of LS_DBDX.ZDBCS
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public Integer getZdbcs() {
        return zdbcs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.ZDBCS
     *
     * @param zdbcs the value for LS_DBDX.ZDBCS
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setZdbcs(Integer zdbcs) {
        this.zdbcs = zdbcs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.CGCSHF
     *
     * @return the value of LS_DBDX.CGCSHF
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public String getCgcshf() {
        return cgcshf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.CGCSHF
     *
     * @param cgcshf the value for LS_DBDX.CGCSHF
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setCgcshf(String cgcshf) {
        this.cgcshf = cgcshf == null ? null : cgcshf.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.DBSXHF
     *
     * @return the value of LS_DBDX.DBSXHF
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public String getDbsxhf() {
        return dbsxhf;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.DBSXHF
     *
     * @param dbsxhf the value for LS_DBDX.DBSXHF
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setDbsxhf(String dbsxhf) {
        this.dbsxhf = dbsxhf == null ? null : dbsxhf.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.HFNR
     *
     * @return the value of LS_DBDX.HFNR
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public String getHfnr() {
        return hfnr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.HFNR
     *
     * @param hfnr the value for LS_DBDX.HFNR
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setHfnr(String hfnr) {
        this.hfnr = hfnr == null ? null : hfnr.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.ZT
     *
     * @return the value of LS_DBDX.ZT
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.ZT
     *
     * @param zt the value for LS_DBDX.ZT
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.CJRQ
     *
     * @return the value of LS_DBDX.CJRQ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public String getCjrq() {
        return cjrq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.CJRQ
     *
     * @param cjrq the value for LS_DBDX.CJRQ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setCjrq(String cjrq) {
        this.cjrq = cjrq == null ? null : cjrq.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.CJSJ
     *
     * @return the value of LS_DBDX.CJSJ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public String getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.CJSJ
     *
     * @param cjsj the value for LS_DBDX.CJSJ
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setCjsj(String cjsj) {
        this.cjsj = cjsj == null ? null : cjsj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.DLID
     *
     * @return the value of LS_DBDX.DLID
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public Long getDlid() {
        return dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.DLID
     *
     * @param dlid the value for LS_DBDX.DLID
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setDlid(Long dlid) {
        this.dlid = dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.DBLB
     *
     * @return the value of LS_DBDX.DBLB
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public String getDblb() {
        return dblb;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.DBLB
     *
     * @param dblb the value for LS_DBDX.DBLB
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setDblb(String dblb) {
        this.dblb = dblb == null ? null : dblb.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.JMTX
     *
     * @return the value of LS_DBDX.JMTX
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public String getJmtx() {
        return jmtx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.JMTX
     *
     * @param jmtx the value for LS_DBDX.JMTX
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setJmtx(String jmtx) {
        this.jmtx = jmtx == null ? null : jmtx.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.DXTX
     *
     * @return the value of LS_DBDX.DXTX
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public String getDxtx() {
        return dxtx;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.DXTX
     *
     * @param dxtx the value for LS_DBDX.DXTX
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setDxtx(String dxtx) {
        this.dxtx = dxtx == null ? null : dxtx.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DBDX.DXTXDH
     *
     * @return the value of LS_DBDX.DXTXDH
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public String getDxtxdh() {
        return dxtxdh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DBDX.DXTXDH
     *
     * @param dxtxdh the value for LS_DBDX.DXTXDH
     *
     * @ibatorgenerated Thu Apr 17 09:10:59 CST 2014
     */
    public void setDxtxdh(String dxtxdh) {
        this.dxtxdh = dxtxdh == null ? null : dxtxdh.trim();
    }
}