package com.slf.engine.bo;

import java.math.BigDecimal;

import com.slf.engine.base.BaseObj;


public class LsDxhc extends BaseObj {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.DXHCID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private Long dxhcid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.DLID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private Long dlid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.DXPCH
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private Integer dxpch;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.DXNR
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String dxnr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.BZJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private BigDecimal bzj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.CLKSSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String clkssj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.CLJSSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String cljssj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.DSFSSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String dsfssj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.CLS
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private Integer cls;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.JRBZ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String jrbz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.DLFLSH
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String dlflsh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.MBBZ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String mbbz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.CJRQ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String cjrq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.CJSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String cjsj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.CLBZ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String clbz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_DXHC.DXHMQ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    private String dxhmq;
    
    private String spjrh;
    
    private Long hdmbid;

    public Long getHdmbid() {
		return hdmbid;
	}

	public void setHdmbid(Long hdmbid) {
		this.hdmbid = hdmbid;
	}

	public String getSpjrh() {
		return spjrh;
	}

	public void setSpjrh(String spjrh) {
		this.spjrh = spjrh;
	}

	/**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.DXHCID
     *
     * @return the value of LS_DXHC.DXHCID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public Long getDxhcid() {
        return dxhcid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.DXHCID
     *
     * @param dxhcid the value for LS_DXHC.DXHCID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setDxhcid(Long dxhcid) {
        this.dxhcid = dxhcid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.DLID
     *
     * @return the value of LS_DXHC.DLID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public Long getDlid() {
        return dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.DLID
     *
     * @param dlid the value for LS_DXHC.DLID
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setDlid(Long dlid) {
        this.dlid = dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.DXPCH
     *
     * @return the value of LS_DXHC.DXPCH
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public Integer getDxpch() {
        return dxpch;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.DXPCH
     *
     * @param dxpch the value for LS_DXHC.DXPCH
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setDxpch(Integer dxpch) {
        this.dxpch = dxpch;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.DXNR
     *
     * @return the value of LS_DXHC.DXNR
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getDxnr() {
        return dxnr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.DXNR
     *
     * @param dxnr the value for LS_DXHC.DXNR
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setDxnr(String dxnr) {
        this.dxnr = dxnr == null ? null : dxnr.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.BZJ
     *
     * @return the value of LS_DXHC.BZJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public BigDecimal getBzj() {
        return bzj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.BZJ
     *
     * @param bzj the value for LS_DXHC.BZJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setBzj(BigDecimal bzj) {
        this.bzj = bzj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.CLKSSJ
     *
     * @return the value of LS_DXHC.CLKSSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getClkssj() {
        return clkssj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.CLKSSJ
     *
     * @param clkssj the value for LS_DXHC.CLKSSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setClkssj(String clkssj) {
        this.clkssj = clkssj == null ? null : clkssj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.CLJSSJ
     *
     * @return the value of LS_DXHC.CLJSSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getCljssj() {
        return cljssj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.CLJSSJ
     *
     * @param cljssj the value for LS_DXHC.CLJSSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setCljssj(String cljssj) {
        this.cljssj = cljssj == null ? null : cljssj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.DSFSSJ
     *
     * @return the value of LS_DXHC.DSFSSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getDsfssj() {
        return dsfssj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.DSFSSJ
     *
     * @param dsfssj the value for LS_DXHC.DSFSSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setDsfssj(String dsfssj) {
        this.dsfssj = dsfssj == null ? null : dsfssj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.CLS
     *
     * @return the value of LS_DXHC.CLS
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public Integer getCls() {
        return cls;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.CLS
     *
     * @param cls the value for LS_DXHC.CLS
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setCls(Integer cls) {
        this.cls = cls;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.JRBZ
     *
     * @return the value of LS_DXHC.JRBZ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getJrbz() {
        return jrbz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.JRBZ
     *
     * @param jrbz the value for LS_DXHC.JRBZ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setJrbz(String jrbz) {
        this.jrbz = jrbz == null ? null : jrbz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.DLFLSH
     *
     * @return the value of LS_DXHC.DLFLSH
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getDlflsh() {
        return dlflsh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.DLFLSH
     *
     * @param dlflsh the value for LS_DXHC.DLFLSH
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setDlflsh(String dlflsh) {
        this.dlflsh = dlflsh == null ? null : dlflsh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.MBBZ
     *
     * @return the value of LS_DXHC.MBBZ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getMbbz() {
        return mbbz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.MBBZ
     *
     * @param mbbz the value for LS_DXHC.MBBZ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setMbbz(String mbbz) {
        this.mbbz = mbbz == null ? null : mbbz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.CJRQ
     *
     * @return the value of LS_DXHC.CJRQ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getCjrq() {
        return cjrq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.CJRQ
     *
     * @param cjrq the value for LS_DXHC.CJRQ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setCjrq(String cjrq) {
        this.cjrq = cjrq == null ? null : cjrq.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.CJSJ
     *
     * @return the value of LS_DXHC.CJSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getCjsj() {
        return cjsj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.CJSJ
     *
     * @param cjsj the value for LS_DXHC.CJSJ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setCjsj(String cjsj) {
        this.cjsj = cjsj == null ? null : cjsj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.CLBZ
     *
     * @return the value of LS_DXHC.CLBZ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getClbz() {
        return clbz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.CLBZ
     *
     * @param clbz the value for LS_DXHC.CLBZ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setClbz(String clbz) {
        this.clbz = clbz == null ? null : clbz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_DXHC.DXHMQ
     *
     * @return the value of LS_DXHC.DXHMQ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public String getDxhmq() {
        return dxhmq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_DXHC.DXHMQ
     *
     * @param dxhmq the value for LS_DXHC.DXHMQ
     *
     * @ibatorgenerated Mon Feb 18 17:49:38 CST 2013
     */
    public void setDxhmq(String dxhmq) {
        this.dxhmq = dxhmq;
    }
}