package com.slf.engine.bo;

import com.slf.engine.base.BaseObj;


public class LsMosms extends BaseObj {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MOSMS.DXID
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    private Long dxid;
    
    private String zhm;
    
    

    public String getZhm() {
		return zhm;
	}

	public void setZhm(String zhm) {
		this.zhm = zhm;
	}

	/**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MOSMS.DLID
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    private Long dlid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MOSMS.YYS
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    private String yys;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MOSMS.TDBH
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    private String tdbh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MOSMS.JSH
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    private String jsh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MOSMS.JSHM
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    private String jshm;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MOSMS.JSNR
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    private String jsnr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MOSMS.JSRQ
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    private String jsrq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MOSMS.JSSJ
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    private String jssj;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MOSMS.DXID
     *
     * @return the value of LS_MOSMS.DXID
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public Long getDxid() {
        return dxid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MOSMS.DXID
     *
     * @param dxid the value for LS_MOSMS.DXID
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public void setDxid(Long dxid) {
        this.dxid = dxid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MOSMS.DLID
     *
     * @return the value of LS_MOSMS.DLID
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public Long getDlid() {
        return dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MOSMS.DLID
     *
     * @param dlid the value for LS_MOSMS.DLID
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public void setDlid(Long dlid) {
        this.dlid = dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MOSMS.YYS
     *
     * @return the value of LS_MOSMS.YYS
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public String getYys() {
        return yys;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MOSMS.YYS
     *
     * @param yys the value for LS_MOSMS.YYS
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public void setYys(String yys) {
        this.yys = yys == null ? null : yys.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MOSMS.TDBH
     *
     * @return the value of LS_MOSMS.TDBH
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public String getTdbh() {
        return tdbh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MOSMS.TDBH
     *
     * @param tdbh the value for LS_MOSMS.TDBH
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public void setTdbh(String tdbh) {
        this.tdbh = tdbh == null ? null : tdbh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MOSMS.JSH
     *
     * @return the value of LS_MOSMS.JSH
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public String getJsh() {
        return jsh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MOSMS.JSH
     *
     * @param jsh the value for LS_MOSMS.JSH
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public void setJsh(String jsh) {
        this.jsh = jsh == null ? null : jsh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MOSMS.JSHM
     *
     * @return the value of LS_MOSMS.JSHM
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public String getJshm() {
        return jshm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MOSMS.JSHM
     *
     * @param jshm the value for LS_MOSMS.JSHM
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public void setJshm(String jshm) {
        this.jshm = jshm == null ? null : jshm.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MOSMS.JSNR
     *
     * @return the value of LS_MOSMS.JSNR
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public String getJsnr() {
        return jsnr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MOSMS.JSNR
     *
     * @param jsnr the value for LS_MOSMS.JSNR
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public void setJsnr(String jsnr) {
        this.jsnr = jsnr == null ? null : jsnr.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MOSMS.JSRQ
     *
     * @return the value of LS_MOSMS.JSRQ
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public String getJsrq() {
        return jsrq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MOSMS.JSRQ
     *
     * @param jsrq the value for LS_MOSMS.JSRQ
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public void setJsrq(String jsrq) {
        this.jsrq = jsrq == null ? null : jsrq.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MOSMS.JSSJ
     *
     * @return the value of LS_MOSMS.JSSJ
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public String getJssj() {
        return jssj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MOSMS.JSSJ
     *
     * @param jssj the value for LS_MOSMS.JSSJ
     *
     * @ibatorgenerated Mon Mar 18 19:12:24 CST 2013
     */
    public void setJssj(String jssj) {
        this.jssj = jssj == null ? null : jssj.trim();
    }
}