package com.slf.engine.bo;

import java.math.BigDecimal;

import com.slf.engine.base.BaseObj;

public class LsMtsms extends BaseObj {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.DXID
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private Long dxid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.DLID
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private Long dlid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.JRBZ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String jrbz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.DLFLSH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String dlflsh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.YYS
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String yys;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.JG
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private BigDecimal jg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.TDBH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String tdbh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FSH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String fsh;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FSHM
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String fshm;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FSNR
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String fsnr;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FSRQ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String fsrq;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FSSJ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String fssj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FHSJ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String fhsj;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.ZT
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String zt;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.PCH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String pch;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FPH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private Short fph;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.NRZS
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private Integer nrzs;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.CLJG
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String cljg;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.FSBZ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String fsbz;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.XTFPH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private Short xtfph;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column LS_MTSMS.MBBZ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    private String mbbz;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.DXID
     *
     * @return the value of LS_MTSMS.DXID
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public Long getDxid() {
        return dxid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.DXID
     *
     * @param dxid the value for LS_MTSMS.DXID
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setDxid(Long dxid) {
        this.dxid = dxid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.DLID
     *
     * @return the value of LS_MTSMS.DLID
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public Long getDlid() {
        return dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.DLID
     *
     * @param dlid the value for LS_MTSMS.DLID
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setDlid(Long dlid) {
        this.dlid = dlid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.JRBZ
     *
     * @return the value of LS_MTSMS.JRBZ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getJrbz() {
        return jrbz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.JRBZ
     *
     * @param jrbz the value for LS_MTSMS.JRBZ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setJrbz(String jrbz) {
        this.jrbz = jrbz == null ? null : jrbz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.DLFLSH
     *
     * @return the value of LS_MTSMS.DLFLSH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getDlflsh() {
        return dlflsh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.DLFLSH
     *
     * @param dlflsh the value for LS_MTSMS.DLFLSH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setDlflsh(String dlflsh) {
        this.dlflsh = dlflsh == null ? null : dlflsh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.YYS
     *
     * @return the value of LS_MTSMS.YYS
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getYys() {
        return yys;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.YYS
     *
     * @param yys the value for LS_MTSMS.YYS
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setYys(String yys) {
        this.yys = yys == null ? null : yys.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.JG
     *
     * @return the value of LS_MTSMS.JG
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public BigDecimal getJg() {
        return jg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.JG
     *
     * @param jg the value for LS_MTSMS.JG
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setJg(BigDecimal jg) {
        this.jg = jg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.TDBH
     *
     * @return the value of LS_MTSMS.TDBH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getTdbh() {
        return tdbh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.TDBH
     *
     * @param tdbh the value for LS_MTSMS.TDBH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setTdbh(String tdbh) {
        this.tdbh = tdbh == null ? null : tdbh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FSH
     *
     * @return the value of LS_MTSMS.FSH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getFsh() {
        return fsh;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FSH
     *
     * @param fsh the value for LS_MTSMS.FSH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setFsh(String fsh) {
        this.fsh = fsh == null ? null : fsh.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FSHM
     *
     * @return the value of LS_MTSMS.FSHM
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getFshm() {
        return fshm;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FSHM
     *
     * @param fshm the value for LS_MTSMS.FSHM
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setFshm(String fshm) {
        this.fshm = fshm == null ? null : fshm.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FSNR
     *
     * @return the value of LS_MTSMS.FSNR
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getFsnr() {
        return fsnr;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FSNR
     *
     * @param fsnr the value for LS_MTSMS.FSNR
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setFsnr(String fsnr) {
        this.fsnr = fsnr == null ? null : fsnr.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FSRQ
     *
     * @return the value of LS_MTSMS.FSRQ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getFsrq() {
        return fsrq;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FSRQ
     *
     * @param fsrq the value for LS_MTSMS.FSRQ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setFsrq(String fsrq) {
        this.fsrq = fsrq == null ? null : fsrq.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FSSJ
     *
     * @return the value of LS_MTSMS.FSSJ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getFssj() {
        return fssj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FSSJ
     *
     * @param fssj the value for LS_MTSMS.FSSJ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setFssj(String fssj) {
        this.fssj = fssj == null ? null : fssj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FHSJ
     *
     * @return the value of LS_MTSMS.FHSJ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getFhsj() {
        return fhsj;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FHSJ
     *
     * @param fhsj the value for LS_MTSMS.FHSJ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setFhsj(String fhsj) {
        this.fhsj = fhsj == null ? null : fhsj.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.ZT
     *
     * @return the value of LS_MTSMS.ZT
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getZt() {
        return zt;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.ZT
     *
     * @param zt the value for LS_MTSMS.ZT
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setZt(String zt) {
        this.zt = zt == null ? null : zt.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.PCH
     *
     * @return the value of LS_MTSMS.PCH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getPch() {
        return pch;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.PCH
     *
     * @param pch the value for LS_MTSMS.PCH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setPch(String pch) {
        this.pch = pch == null ? null : pch.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FPH
     *
     * @return the value of LS_MTSMS.FPH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public Short getFph() {
        return fph;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FPH
     *
     * @param fph the value for LS_MTSMS.FPH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setFph(Short fph) {
        this.fph = fph;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.NRZS
     *
     * @return the value of LS_MTSMS.NRZS
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public Integer getNrzs() {
        return nrzs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.NRZS
     *
     * @param nrzs the value for LS_MTSMS.NRZS
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setNrzs(Integer nrzs) {
        this.nrzs = nrzs;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.CLJG
     *
     * @return the value of LS_MTSMS.CLJG
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getCljg() {
        return cljg;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.CLJG
     *
     * @param cljg the value for LS_MTSMS.CLJG
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setCljg(String cljg) {
        this.cljg = cljg == null ? null : cljg.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.FSBZ
     *
     * @return the value of LS_MTSMS.FSBZ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getFsbz() {
        return fsbz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.FSBZ
     *
     * @param fsbz the value for LS_MTSMS.FSBZ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setFsbz(String fsbz) {
        this.fsbz = fsbz == null ? null : fsbz.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.XTFPH
     *
     * @return the value of LS_MTSMS.XTFPH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public Short getXtfph() {
        return xtfph;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.XTFPH
     *
     * @param xtfph the value for LS_MTSMS.XTFPH
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setXtfph(Short xtfph) {
        this.xtfph = xtfph;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column LS_MTSMS.MBBZ
     *
     * @return the value of LS_MTSMS.MBBZ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public String getMbbz() {
        return mbbz;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column LS_MTSMS.MBBZ
     *
     * @param mbbz the value for LS_MTSMS.MBBZ
     *
     * @ibatorgenerated Tue Mar 05 11:32:33 CST 2013
     */
    public void setMbbz(String mbbz) {
        this.mbbz = mbbz == null ? null : mbbz.trim();
    }
}